//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pgm02a.rc
//

#define EDITWINDOW             100

#define CM_FILENEW            (WM_USER + 101)
#define CM_FILEOPEN           (WM_USER + 102)
#define CM_FILESAVE           (WM_USER + 103)
#define CM_FILESAVEAS         (WM_USER + 104)
#define CM_EXIT               (WM_USER + 105)
#define CM_EDITUNDO           (WM_USER + 106)
#define CM_EDITCUT            (WM_USER + 107)
#define CM_EDITCOPY           (WM_USER + 108)
#define CM_EDITPASTE          (WM_USER + 109)
#define CM_EDITCLEAR          (WM_USER + 110)
#define CM_HELPABOUT          (WM_USER + 111)
#define CM_FONTCHANGE         (WM_USER + 112)

#define IDS_MAINTITLE     2000  // frame window's title
#define IDS_WINNAME       2001  // GetClassName's wndclass name
#define IDS_INITFONT      2002  // name system font
#define IDS_MSG_NOTSAVE   2003  // file not saved msg
#define IDS_MSG_QUIT      2004  // quit application query msg
#define IDS_MSG_QUERY     2005  // title of quit query messagebox
#define IDS_MSG_ERROR     2006  // error has occurred
#define IDS_MSG_NOMEM     2007  // out of memory
#define IDS_MSG_FILEERR   2008  // file save error
#define IDS_MSG_FILEOPEN  2009  // file open error
#define IDS_MSG_NOBAR     2010  // no scroll bars error
#define IDS_MSG_FILEWRT   2011  // file save error - I/O fail
#define IDS_MSG_FILEREAD  2012  // file read error
#define IDS_MSG_FILEBIG   2013  // file size too large
#define IDS_UNTITLED      2014  // untitled file message

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
